# Workflow GitHub Actions - Build e Deploy de Angular 20 no Azure App Service
# Autor: Sergio Mendes

name: Build and deploy Angular app to Azure Web App - agendaweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular app (production)
        run: npm run build -- --configuration=production

      - name: Add web.config for Angular routing
        run: |
          echo ^<configuration^> > dist/agendaWeb/browser/web.config
          echo ^  ^<system.webServer^> >> dist/agendaWeb/browser/web.config
          echo ^    ^<rewrite^> >> dist/agendaWeb/browser/web.config
          echo ^      ^<rules^> >> dist/agendaWeb/browser/web.config
          echo ^        ^<rule name="Angular Routes" stopProcessing="true"^> >> dist/agendaWeb/browser/web.config
          echo ^          ^<match url=".*" /^> >> dist/agendaWeb/browser/web.config
          echo ^          ^<conditions logicalGrouping="MatchAll"^> >> dist/agendaWeb/browser/web.config
          echo ^            ^<add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" /^> >> dist/agendaWeb/browser/web.config
          echo ^            ^<add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" /^> >> dist/agendaWeb/browser/web.config
          echo ^          ^</conditions^> >> dist/agendaWeb/browser/web.config
          echo ^          ^<action type="Rewrite" url="/index.html" /^> >> dist/agendaWeb/browser/web.config
          echo ^        ^</rule^> >> dist/agendaWeb/browser/web.config
          echo ^      ^</rules^> >> dist/agendaWeb/browser/web.config
          echo ^    ^</rewrite^> >> dist/agendaWeb/browser/web.config
          echo ^    ^<defaultDocument^> >> dist/agendaWeb/browser/web.config
          echo ^      ^<files^> >> dist/agendaWeb/browser/web.config
          echo ^        ^<add value="index.html" /^> >> dist/agendaWeb/browser/web.config
          echo ^      ^</files^> >> dist/agendaWeb/browser/web.config
          echo ^    ^</defaultDocument^> >> dist/agendaWeb/browser/web.config
          echo ^  ^</system.webServer^> >> dist/agendaWeb/browser/web.config
          echo ^</configuration^> >> dist/agendaWeb/browser/web.config

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-dist
          path: dist/agendaWeb/browser

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B44EC8BE5D474473B5E24D32C16605F3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9A373294E5364781996CA69CFF075521 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_94DE9DF4BEB840CF8B97F58C47FFAD4E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'agendaweb'
          slot-name: 'Production'
          package: dist/agendaWeb/browser
